### ISSUE TITLE
Steps for the deploying the bundle to the the ODL in karaf.

### ISSUE THREAD

**Issue by subh007** [sniggel/odl-mdsal-cup-example#1]
Could you please explain the steps required to deploy the toaster example to ODL karaf distribution.

**Comment by sniggel** [comment]
The toaster example should already be in the controller under
opendaylight/md-sal/samples/

I am unsure of where you are starting from, so I will assume you got the
latest controller from gerrit. Here are the steps to deploy the toaster:
1. get odlparent from gerrit (
https://git.opendaylight.org/gerrit/#/admin/projects/odlparent) and compile
it.
2. get the controller from gerrit (
https://git.opendaylight.org/gerrit/#/admin/projects/controller) and
compile it.
3. extract karaf from
controller/karaf/opendaylight-karaf/target/distribution.opendaylight-karaf-1.5.0-SNAPSHOT
4. run karaf
from controller/karaf/opendaylight-karaf/target/distribution.opendaylight-karaf-1.5.0-SNAPSHOT/bin/karaf
5. use this command to install the toaster: feature:install odl-toaster
odl-toaster-rest odl-toaster-ui

You could also use any stable release if you want, in that case just use
step #5 to install the toaster



On Sun, Feb 8, 2015 at 2:33 PM, Subhash Kumar Singh <
notifications@github.com> wrote:

> Could you please explain the steps required to deploy the toaster example
> to ODL karaf distribution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sniggel/odl-mdsal-cup-example/issues/1>.
>



-- 
Cordialement,

Gabriel Robitaille-Montpetit
grmontpetit@gmail.com
Cell 514-991-8187

**Comment by subh007** [comment]
Thanks @sniggel for the response.

I am following the opendaylight wiki https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL:Toaster_Step-By-Step for writing sample application.

I am not able to understand the xml (03-toaster-sample.xml https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL:Toaster_Step-By-Step#Define_the_initial_XML_configuration) deployment for the self build bundle.

Could you please tell me how to use above xml file for the self build bundle deployment.

**Comment by sniggel** [comment]
Sure,

I will assume that you got the controller from gerrit. The config file is
already present in the controller in
controller/opendaylight/md-sal/samples/toaster-config, you can understand
how this file is done by looking at the toaster example.

As for the deployment, look in
controller/features/mdsal/src/main/resources/features.xml

You should see a section "odl-toaster" with a config file name. That's how
the config is deployed to the config pusher.



On Mon, Feb 9, 2015 at 12:33 AM, Subhash Kumar Singh <
notifications@github.com> wrote:

> Thanks @sniggel <https://github.com/sniggel> for the response.
>
> I am following the opendaylight wiki
> https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL:Toaster_Step-By-Step
> for writing sample application.
>
> I am not able to understand the xml (03-toaster-sample.xml
> https://wiki.opendaylight.org/view/OpenDaylight_Controller:MD-SAL:Toaster_Step-By-Step#Define_the_initial_XML_configuration)
> deployment for the self build bundle.
>
> Could you please tell me how to use above xml file for the self build
> bundle deployment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sniggel/odl-mdsal-cup-example/issues/1#issuecomment-73459660>
> .
>



-- 
Cordialement,

Gabriel Robitaille-Montpetit
grmontpetit@gmail.com
Cell 514-991-8187

**Comment by subh007** [comment]
Thanks @sniggel  for all your explanation.
I used the `bundle:install file//<path for the jar>` command, and I tested that toaster example is working.
