### ISSUE TITLE
RPC-not supported error

### ISSUE THREAD

**Issue by c3m3gyanesh** [sniggel/odl-mdsal-cup-example#2]
I tried this code with Stable branch of Controller - helium code base. I am getting a RPC error:

{
  "errors": {
    "error": [
      {
        "error-type": "rpc",
        "error-tag": "operation-not-supported",
        "error-message": "No implementation for this operation is available."
      }
    ]
  }
}

**Comment by sniggel** [comment]
Hi,

You might want to work from master. I will be revisiting this project today because I want to include a features file, a distribution and update the artifacts.

**Comment by c3m3gyanesh** [comment]
When i try with master branch, the feature addition step results in error. I added the details in the mdsal/features.xml file. But "mvn clean install" results in "  The bundle "org.opendaylight.controller.cprest-consumer_0.0.1.SNAPSHOT [199]" could not be resolved. Reason: Missing Constraint: Import-Package: com.google.common.collect; version="[14.0.0,15.0.0)" ".
Please update the version of the dependency properly. I tried to fix it, but couldn't.

**Comment by sniggel** [comment]
Oh yeah, I remember this from another project. Just add an entry above the
other entries in the features section (you might have to add wrap):
<bundle>mvn:com.google.collections/google-collections/1.0</bundle>




On Thu, Mar 26, 2015 at 1:59 PM, c3m3gyanesh <notifications@github.com>
wrote:

> When i try with master branch, the feature addition step results in error.
> I added the details in the mdsal/features.xml file. But "mvn clean install"
> results in " The bundle
> "org.opendaylight.controller.cprest-consumer_0.0.1.SNAPSHOT [199]" could
> not be resolved. Reason: Missing Constraint: Import-Package:
> com.google.common.collect; version="[14.0.0,15.0.0)" ".
> Please update the version of the dependency properly. I tried to fix it,
> but couldn't.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sniggel/odl-mdsal-cup-example/issues/2#issuecomment-86647754>
> .
>



-- 
Cordialement,

Gabriel Robitaille-Montpetit
grmontpetit@gmail.com
Cell 514-991-8187

**Comment by c3m3gyanesh** [comment]
thanks for the input. But i am still having the problem I think this need another package from google Guava. I tried to add that dependency in cup-consumer/pom.xml file. But still i have the same problem.

**Comment by sniggel** [comment]
Have you tried also adding this in the features (before the other features): 
    <feature name='odl-cup' version='0.0.1-SNAPSHOT' description="OpenDaylight :: Cup">
        <feature version='${yangtools.version}'>odl-yangtools-common</feature>
        <feature version='${yangtools.version}'>odl-yangtools-binding</feature>
        <feature version='${project.version}'>odl-mdsal-broker</feature>
	<bundle>mvn:com.google.collections/google-collections/1.0</bundle>
	<bundle>mvn:com.google.guava/guava/14.0</bundle>
        <bundle>mvn:org.opendaylight.controller/cup/0.0.1-SNAPSHOT</bundle>
        <bundle>mvn:org.opendaylight.controller/cup-consumer/0.0.1-SNAPSHOT</bundle>
        <bundle>mvn:org.opendaylight.controller/cup-provider/0.0.1-SNAPSHOT</bundle>
        <configfile finalname="${config.configfile.directory}/${config.cup.configfile}">mvn:org.opendaylight.controller/cup-config/0.0.1-SNAPSHOT/xml/config</configfile>
    </feature>

**Comment by c3m3gyanesh** [comment]
i will try this. Any idea why the RPC was not working on Stable branch of helium. I tried with the toaster example also. That was also not working.

**Comment by sniggel** [comment]
Well, the RPC error that you describes is saying it cannot find the implementation (probably the cup-provider). You can diagnose this in two ways:
1. In the karaf shell, type bundle:list and check if the cup, cup-provider and cup-consumer bundles are correctly installed (active).
2. Swagger is used to generate the endpoints documentation, you can access this API doc by installing it within the karaf shell: feature:install odl-mdsal-apidoc and pointing your browser to http://localhost:8181/apidoc/explorer/ . In that page, you should see cup, cup-provider and cup-consumer and can expand these items to see how to use the corresponding API.

**Comment by c3m3gyanesh** [comment]
Yes.. i used the API doc. It is visible on the page. I tried to put input to check the RPC and get the error as i mentioned. That's why i was confused. It is like the initial "creatInstance" function is not being called. I am not sure.

**Comment by c3m3gyanesh** [comment]
Do you have any idea about this exception. I am getting this exception after i do feature:install old-cup.
If you have faced this issue, then let me know

feature:install odl-mdsal-alException in thread "config-pusher" java.lang.IllegalStateException: Max wait for capabilities reached.Not enough capabilities for 03.cup.xml(odl-cup,odl-cup). Expected but not found: [urn:opendaylight:params:xml:ns:yang:controller:config:cup-provider:impl?module=cup-provider-impl&revision=2014-11-16]

**Comment by sniggel** [comment]
1) The config-pusher error you are seeing is related to the required-capabilities defined in the 02-cup.xml and it means it cannot find the cup-provider-impl module (it's defined in the same file). This can happen if the cup-provider bundle cannot find all the required dependencies.
2) For the openflowplugin, dlux and l2switch: just check if these features have been defined within the controller features file (controller/features/ANYPROJECT/src/main/resources/features.xml). Then you can install them using the feature:install command.
